spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
spring.batch.job.names: ${job.name:NONE}
